name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:



jobs:
  checkForTests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Check if files exist
        run: |
          if [ -f $GITHUB_WORKSPACE/main_test.py ]; then
            echo "File exists"
            echo 0 > error.txt
          else
            echo "File does not exist"
            exit 1 > error.txt
          fi
      - name: Load artifact
        uses: actions/upload-artifact@v4
        with:
          name: file_exists
          path: error.txt
          retention-days: 1
          
  build:
    needs: checkForTests
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.9.12, 3.11.0, 3.12.3] #3.10.4
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: file_exists

      - name: Check artifact
        shell: bash
        run: |
          value=`cat error.txt`
          rm error.txt
          if [ "$value" -gt 0 ]; then
                  echo "no file"
                  exit 1
          fi

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test
        run: pytest
