name: Validate python versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:



jobs:
  checkForTests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit

      - name: Check if files exist
        run: |
          if [ -f $GITHUB_WORKSPACE/main_test.py ]; then
            echo "File exists"
          else
              echo "File does not exist"
              exit 1
          fi
  build:
    needs: checkForTests
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.10.11]
    steps:
      - uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: pytest
